blank_issues_enabled: false
contact_links:
    - name: â“ Nextcloud Server Community Support and Help
      url: https://help.nextcloud.com/
      about: Configuration, webserver/proxy or performance issues and other questions
    - name: ğŸ³ Docker Community Support and Help
      url: https://forums.docker.com/
      about: Configuration, installation, networking and other questions
    - name: ğŸ› Nextcloud Server Bug Reports or Enhancement Requests
      url: https://github.com/nextcloud/server/issues/new/choose
      about: Bug reports and feature requests for Nextcloud
